server:
 port: 80
 
spring:
 activemq:
   broker-url: tcp://localhost:61616 
 jms:
   pub-sub-domain: true  #发布点对点模型
   template:
    default-destination: itheim
 rabbitmq:
   host: localhost
   port: 5672
 kafka:
   bootstrap-servers: localhost:9092
   consumer:
     group-id: order


rocketmq:
 name-server: localhost:9876
 producer:
  group: group_rocketmq

