server:
  port: 80
  
spring:
  datasource:
     druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      username: root
      password: abc123
  devtools:
    restart:
    #设置不参与热部署的文件或文件夹
      exclude: static/**,public/**,config/application.yml
#       enabled: false
      
      
      
#spring:
#  datasource:    
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssm_db
#    username: root
#    password: abc123
#    type: com.alibaba.druid.pool.DruidDataSource
      
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_  
      id-type: auto 
      #id自增策略默认ASSIGN_ID
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     