#spring:
#  datasource:   
#    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
#    hikari:
#       driver-class-name: com.mysql.cj.jdbc.Driver
#       username: root
#       password: abc123
#       maximum-pool-size: 50


#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tbl_
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# h2数据库

server:
  port: 80
spring:
  h2:
   console:
      enabled: true
      path: /h2

#访问时报错，配置好数据源初始化好，之后就不需要了
  datasource:   
    url: jdbc:h2:~/test
    hikari:
#       driver-class-name: org.h2.Driver
       username: sa
       password: 123456
       maximum-pool-size: 50
       
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
       
