spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatisplus_db?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: abc123
# 开启mp的日志（输出到控制台）
mybatis-plus:
 configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      
    
